### ISSUE TITLE
node-red-node-serialport node makes the Docker container infinite boot cycle

### ISSUE THREAD

**Issue by joaquimBS** [node-red/node-red-nodes#894]
### Which node are you reporting an issue on?
node-red-node-serialport 1.0.1

### What are the steps to reproduce?
Design a Flow using nodered 2.2.2
The design must have node-red-node-serialport installed
Add a serial-in node and select /dev/ttyUSB0
Enable the node and Deploy

It is worth mentioning the same Flow was working just fine.
I was using NodeRed 2.0.4 and node-red-node-serialport 0.x.x one hour ago.
It is also worth mentioning I can successfully open the /dev/ttyUSB0 port using minicom

### What happens?
Soon after Deploy is clicked, I see a message saying "Lost connection to the server".
I check the Docker container logs and see the container permanently boot cycling.

![imatge](https://user-images.githubusercontent.com/5919626/159185977-f5c355fe-0ae0-43f2-b7bd-80e26b3c9986.png)

### What do you expect to happen?
The Flow to be deployed and the serial node to start receiving data from the port

### Please tell us about your environment:

![imatge](https://user-images.githubusercontent.com/5919626/159185822-20fc2701-097a-4204-8993-4f0159f095b6.png)

- [x] Node-RED version: 2.2.2
- [ ] node.js version:
- [ ] npm version:
- [x] Platform/OS: Docker on Raspberry Pi 4
- [x] Browser: Firefox

**Comment by csmale** [comment]
This is also logged as:
https://github.com/node-red/node-red/issues/3461
But it fits better here because it is related to node-red-node-serialport and not the core code

**Comment by hardillb** [comment]
Work around https://github.com/node-red/node-red/issues/3461#issuecomment-1076348639

Upstream issue: https://github.com/serialport/node-serialport/issues/2438

**Comment by thomasvnl** [comment]
Issue still not fixed after all this time. Trying the work around...

**Comment by hardillb** [comment]
@thomasvnl the problem is with the node-serialport, until they fix there is nothing we can do.

**Comment by fguiet** [comment]
Hi,

Just to mention here (in order to share the information) that I got the same problem.
I temporaly fixed the issue using the following method:

My docker-compose file

```yaml
version: '3.7'

services:
   node-red:
      # Update 2021/11/02
      #image: nodered/node-red:2.1.3-14
      #image: nodered/node-red:2.0.6-14
      #image: nodered/node-red:2.2.1-16
      # Update 2022/12/21
      image: nodered/node-red:3.0.2-18
      container_name: nodered
      restart: unless-stopped

      # Use Node-red as root, to allow SERIAL usage
      user: root:root

      devices:
        # Expose SERIAL port to container
        - /dev/ttyUSB_TELEINFO:/dev/ttyUSB_TELEINFO
        - /dev/ttyUSB_ZIGBEE:/dev/ttyUSB_ZIGBEE
        # GPIO exposes through PiGPIO daemon : See http://abyz.me.uk/rpi/pigpio/ on port 8888
      environment:
        - TZ=Europe/Paris
        - FLOWS=home_flows.json
      volumes:
        - ./data:/data
        - /etc/localtime:/etc/localtime:ro
        # flow debug file in here
        - ./log:/log
      ports:
        - 1880:1880
```



```bash
# Prerequisites : comment lines devices in docker-compose file, node-red-node-serialport is on version 1.0.1
# docker-compose up -d
cd /data
bash-5.1# npm rebuild --build-from-source
rebuilt dependencies successfully
exit
docker-compose down
# uncomment lines devices in docker-compose file
docker-compose up -d
# Yeah! no more segmentation fault !
```

Hope this help others!
